name: spectre
description: Graphics Library
version: 0.5.0
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/spectre
dependencies:
  unittest: any
  marker_prof:
    git: https://github.com/johnmccutchan/markerprof.git
  vector_math:
    git: https://github.com/johnmccutchan/DartVectorMath.git
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  property_map: any
  browser: any